server:
  port: 9010
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3308/WeiBo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000ms
  mail:
    username: A19861577050@126.com
    password: VRv3uuraf5zb32Uf
    host: smtp.126.com
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li1VgdcfCCkPne5i
            client-secret: 38205fdf4a46ab93958af743309202f266673117
#            redirect-uri: http://localhost:9010/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login # 或 email, name 等
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9010/auth/realms/WeRun/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size : 10MB
      max-request-size : 10MB
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Ov23li1VgdcfCCkPne5i
#            client-secret: 38205fdf4a46ab93958af743309202f266673117
#            redirect-uri: http://localhost:9010/login/oauth2/code/github
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:9010/auth/realms/WeRun/protocol/openid-connect/certs
logging:
  level:
    org.example.auth: debug
