spring:
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
      routes:

        - id: service-post
          uri: lb://service-post
          predicates:
            - Path=/weibo/post/**

        - id: service-friend
          uri: lb://service-friend
          predicates:
            - Path=/weibo/friend/**

