spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.128:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://192.168.11.128:3308/nacos?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
server:
  port: 8080